<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EpochSim.Execution\EpochSim.Execution.csproj" />
    <ProjectReference Include="..\..\src\EpochSim.Samples\EpochSim.Samples.csproj" />
    <ProjectReference Include="..\..\src\EpochSim.Serialization\EpochSim.Serialization.csproj" />
  </ItemGroup>

</Project>
